### ISSUE TITLE
Cant Add Plugin

### ISSUE THREAD

**Issue by trijitdey** [dpa99c/cordova-plugin-request-location-accuracy#1]
cordova plugin add cordova-plugin-diagnostic

```
Fetching plugin "cordova-plugin-diagnostic" via plugin registry
Error: 404 Not Found: cordova-plugin-diagnostic
    at RegClient.<anonymous> (C:\Users\Trijit\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\lib\request.js:268:14)
    at Request.self.callback (C:\Users\Trijit\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:148:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\Trijit\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:876:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\Trijit\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:827:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

**Comment by dpa99c** [comment]
The plugin ID is `cordova.plugins.diagnostic` not `cordova-plugin-diagnostic` as stated in the [installation instructions](https://github.com/dpa99c/cordova-diagnostic-plugin#installation):

```
cordova plugin add cordova.plugins.diagnostic
```
